Repository crypto-com/chain-desktop-wallet, pull requests merged in 2021-11, with the labels that each got.

#771 Problem: Refactor WalletService into smaller purpose
  src/service/TransactionHistoryService.ts
  src/service/TransactionSenderService.ts
  src/service/WalletService.ts
Labels: do not merge yet

#785 Feature: Address book
  .eslintrc.js
  src/components/AddressBookInput/AddressBookInput.tsx
  src/components/AddressBookModal/AddAddressModal.tsx
  src/components/ConfirmModal.tsx/ConfirmModal.tsx
  src/layouts/home/home.tsx
  src/models/AddressBook.ts
  src/pages/assets/components/FormSend.less
  src/pages/assets/components/FormSend.tsx
  src/pages/route.tsx
  src/pages/settings/settings.tsx
  src/pages/settings/tabs/addressBook/AddressBookTab.tsx
  src/recoil/atom.tsx
  src/service/AddressBookService.ts
  src/service/rpc/clients/EVMClient.spec.ts
  src/storage/DatabaseManager.ts
  src/storage/StorageService.ts
Labels: QA, do not merge yet

#808 Feature (Fix #805): Allow users to specify manually destination address during bridge transactions
  src/components/RowAmountOption/RowAmountOption.tsx
  src/language/en-US.json
  src/language/ko-KR.json
  src/language/zh-CN.json
  src/language/zh-HK.json
  src/pages/bridge/bridge.tsx
  src/pages/bridge/components/CronosBridgeForm.less
  src/pages/bridge/components/CronosBridgeForm.tsx
  src/service/TransactionRequestModels.ts
  src/service/bridge/BridgeService.ts
Labels: QA, do not merge yet

#781 Problem: Validator APY and uptime additions
  src/components/ValidatorPowerPercentBar/ValidatorPowerPercentBar.tsx
  src/language/ar-AE.json
  src/language/de-DE.json
  src/language/es-ES.json
  src/language/fr-FR.json
  src/language/ig-NG.json
  src/language/it-IT.json
  src/language/tr-TR.json
  src/language/vi-VN.json
  src/language/zh-HK.json
  src/models/Transaction.ts
  src/pages/home/components/RedelegateFormComponent.tsx
  src/pages/staking/components/RedelegateFormComponent.tsx
  src/pages/staking/components/UndelegateFormComponent.tsx
  src/pages/staking/components/ValidatorListTable.tsx
  src/pages/staking/staking.tsx
  src/service/TransactionHistoryService.ts
  src/service/WalletService.ts
  src/service/rpc/ChainIndexingAPI.ts
  src/service/rpc/ChainIndexingModels.ts
Labels: QA, do not merge yet

#825 bugfix: Address Book
  src/components/AddressBookInput/AddressBookInput.tsx
  src/components/AddressBookModal/AddAddressModal.tsx
  src/components/ConfirmModal/ConfirmModal.tsx
  src/pages/settings/tabs/AddressBook/AddressBook.tsx
Labels: bug
